# Site
title: "Professor Plate's Notebook"
description: "Essays, arguments, and notes in progress"
url: "https://buildlittleworlds.github.io"
baseurl: "/my-ai-notebook"            # project site, so we need the repo name
timezone: "America/Chicago"  # change to your zone

# Build
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title/

# Collections (no 'posts' here — posts are built-in via _posts/)
collections:
  romantic:
    output: true
    permalink: /romantic/:name/
  ai_hermeneutics:
    output: true
    permalink: /ai-hermeneutics/:name/
  archive:
    output: true
    permalink: /archive/:name/
  debate:
    output: true
    permalink: /debate/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:title/"
  - scope:
      path: ""
      type: "romantic"
    values:
      layout: "kit"
  - scope:
      path: ""
      type: "ai_hermeneutics"
    values:
      layout: "kit"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "archive"
  - scope:
      path: ""
      type: "debate"
    values:
      layout: "debate"

# Plugins (optional; all are whitelisted by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - all-blog-in-one-file/
  - backups/
  - planning-posts/
  - vendor/
  - node_modules/
  - .github/
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - README.md
